#!/usr/bin/env bash
set -e

if [ -z "$1" ]; then
	printf '%b\n' "$(cat ~/src/github/config/vim/README.md)"
else
	printf '%b\n' "$(cat ~/src/github/config/vim/README.md|grep -i -A 2 -B 2 --color=always $1)"
fi

